### ISSUE TITLE
依赖下载的问题

### ISSUE THREAD

**Issue by GaussYuan191** [lp-Imagine/react-node-admin#1]
想问下 你的 node和npm版本是多少 ，
[4/7] ⠂ node-sass
error E:\Code\React\react-backgrounds\node_modules\core-js-pure: Command failed.
Exit code: 1
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments:

**Comment by lp-Imagine** [comment]
Node.js 14.10.1

**Comment by GaussYuan191** [comment]
你好 我换了node的版本 npm i 的时候会出现这样的错误 想问下你react的版本是用的多少啊
npm ERR! While resolving: react-backgrounds@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @jiaminghi/data-view-react@1.2.5
npm ERR! node_modules/@jiaminghi/data-view-react
npm ERR!   @jiaminghi/data-view-react@"^1.2.5" from the root project

**Comment by lp-Imagine** [comment]
17.0.2
